name: Build DLL

on:
  push:
    branches:
      - main
      - master

  pull_request:

  workflow_dispatch:


jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2


      - name: Build Release x64
        shell: cmd
        run: |
          msbuild IdaLovesMe.sln ^
            /p:Configuration=Release ^
            /p:Platform=x64 ^
            /p:UsePrecompiledHeader=false ^
            /m


      - name: Find DLL
        shell: cmd
        run: |
          dir /s /b *.dll


      - name: Upload DLL
        uses: actions/upload-artifact@v4
        with:
          name: built-dll
          path: |
            **/Release/**/*.dll
            **/x64/Release/**/*.dll
