name: Build DLL

on:
  push:
    branches:
      - main
      - master

  pull_request:

  workflow_dispatch:


jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2


      - name: Disable PCH
        shell: powershell
        run: |
          (Get-Content IdaLovesMe\IdaLovesMe.vcxproj) `
          -replace '<PrecompiledHeader>Use</PrecompiledHeader>', '<PrecompiledHeader>NotUsing</PrecompiledHeader>' `
          -replace '<PrecompiledHeader>UseForBuild</PrecompiledHeader>', '<PrecompiledHeader>NotUsing</PrecompiledHeader>' `
          | Set-Content IdaLovesMe\IdaLovesMe.vcxproj


      - name: Build Release x64
        shell: cmd
        run: |
          msbuild IdaLovesMe.sln ^
            /p:Configuration=Release ^
            /p:Platform=x64 ^
            /m


      - name: Find DLL
        shell: cmd
        run: |
          dir /s /b *.dll


      - name: Upload DLL
        uses: actions/upload-artifact@v4
        with:
          name: IdaLovesMe-DLL
          path: |
            **\x64\Release\*.dll
            **\Release\*.dll
